---
- hosts: all
  become: true

  tasks:

  - name: Verifico SSH Centos
    ansible.builtin.systemd_service:
      name: sshd
      state: started
      enabled: true
    when: ansible_os_family == "RedHat"

  - name: Verifico SSH Ubuntu
    ansible.builtin.systemd_service:
      name: ssh
      state: started
      enabled: true
    when: ansible_os_family == "Debian"    

        
